grid_map_topic: /hector_nav2/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: probability
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: probability
     data_min: -8
     data_max: 5
